### ISSUE TITLE
Very good blog post and example

### ISSUE THREAD

**Issue by kspokas** [mschmulen/ios7-javascript-bridge#5]
Overall, I think the writeup and accompanying example do a good job explaining the new ability to natively bridge javascript with Objective-C.   The potential for simplified iOS development and code re-use is definitely of interest.

Some of the transitions between sections in the write-up are a bit abrupt, in that there could be a bit more tying everything together.

One small correction is in the "Simple Execution" code snippet, the expression evaluated ("2 + 8") does not match the log output ("2 + 2").

**Comment by mschmulen** [comment]
Thanks, Kspokas. 

I updated the the post a bit , and the app a lot.  Specifically I added multiple js demo files resolving the "2+2 ", "2 + 8 " issue.
